# name: A name of the experiment
# description: A description of the experiment. It is not used in the program
#
# load: Load the networks’ parameters from the entire path. Format: (environment)/(description)/(step)
# load_inverse: Load feature extractor inverse network parameters from the specific file. Format: (environment)/(description)/(step)
# load_predictor: Load predictor network parameters from the specific file. Format: (environment)/(description)/(step)
# load_controller: Load controller network parameters from the specific file. Format: (environment)/(description)/(step)
#
# device: The program uses the cpu in purpose
# visualize: The window is showed
# skip_log: The log won't be written
# skip_save: The model won’t be saved
# save_interval: Per how many steps to save the model
#
# step_max: Max step of one episode
# progress_interval: Per how many steps to print the progress
# agent_speed: Set the agent's moving speed
# random_policy: The agent chooses a random action
#
# feature_extractor_inverse_lr
# predictor_lr
# controller_lr
# policy_discount
# entropy_discount
# intrinsic_reward_discount
# gamma
#
# feature_size
# hidden_state_size
# feature_extractor_module
# inverse_module
# feature_predictor_module
# inner_state_predictor_module
# controller_module

name: test
description: test # Not used

load: None
load_feature_extractor: None
load_inverse: None
load_inner_state_predictor: None
load_feature_predictor: None
load_controller: None

device: cuda
visualize: False
skip_log: True
skip_save: True
save_interval: 1000

step_max: 5000
progress_interval: 1000
inverse_accuracy_batch_size: 1000 # = progress_interval if 0
agent_speed: 10
random_policy: False
noise_scale: 3.0

inverse_module_predictor_lr: 1e-3
inverse_module_predictor_optimizer: sgd
controller_lr: 1e-4
controller_optimizer: sgd
policy_discount: 0.2
entropy_discount: 0.0
intrinsic_reward_discount: 0.5
predictor_loss_discount: 0.25
gamma: 0.99

feature_size: 256
hidden_state_size: 256
feature_extractor_module: DefaultCNNFeatureExtractor
inverse_module: CuriosityLinearInverseModule
feature_predictor_module: CuriosityLinearFeaturePredictor
inner_state_predictor_module: DefaultLSTMInnerStatePredictor
controller_module: DefaultDiscreteLinearActorCritic